source 'https://rubygems.org'

gem 'builder'
gem 'nanoc', github: 'nanoc/nanoc', branch: 'master'
gem 'nokogiri'
gem 'pygments.rb'
gem 'rdiscount'
gem 'rubypants'
gem 'sass'
gem 'systemu'
gem 'guard-nanoc'
gem 'adsf'
